Repository onflow/flow-evm-bridge, pull requests merged in 2024-08, with the labels that each got.

#100 Update previewnet deployment
  README.md
  cadence/contracts/standards/EVM.cdc
  cadence/tests/flow_evm_bridge_utils_tests.cdc
  flow.json
Labels: Documentation, Deployment

#104 Add emulator support to deployment script
  README.md
  flow.json
  main.go
Labels: Improvement

#107 Testnet deployment followup
  README.md
  cadence/scripts/utils/get_registry_address.cdc
  cadence/tests/scripts/create_empty_usdc_vault.cdc
  flow.json
  main.go
Labels: Deployment

#110 Improve conversion of EVM addresses
  cadence/scripts/evm/call.cdc
  cadence/scripts/evm/get_balance.cdc
  cadence/transactions/evm/call.cdc
Labels: Improvement

#111 Mainnet prep
  README.md
  cadence/args/bridged-nft-code-chunks-args-mainnet.json
  cadence/args/bridged-token-code-chunks-args-mainnet.json
  cadence/contracts/templates/mainnet/EVMBridgedNFTTemplate.cdc
  cadence/contracts/templates/mainnet/EVMBridgedTokenTemplate.cdc
  flow.json
  main.go
Labels: Documentation, Deployment
